config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sessions#new"
  resources :photos
  resources :images

  # Automatically generates the following routes
  # get "/photos" => "photos#index", as: "photos"
  # get "/photos/new" => "photos#new", as: "new_photo"
  # post "/photos" => "photos#create"
  # get "/photos/:id" => "photos#show", as: "photo"
  # get "/photos/:id/edit" => "photos#edit", as: "edit_photo"
  # patch "/photos/:id" => "photos#update"
  # delete "/photos/:id" => "photos#destroy"

  get "/signup" => "users#new"
  post "/users" => "users#create"

  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :images
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user
    redirect_to "/login", status: :see_other unless current_user
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
    render template: "photos/index"
  end

  def show
    @photo = Photo.find(params[:id])
    render template: "photos/show"
  end

  def new
    @photo = Photo.new
    render template: "photos/new"
  end

  def create
    @photo = Photo.new(
      name: params[:photo][:name],
      born: params[:photo][:born],
      description: params[:photo][:description],
    )

    if @photo.save
      redirect_to "/photos"
    else
      render json: { errors: @photo.errors.full_messages }, status: unprocessable_entity
    end
  end

  def edit
    @photo = Photo.find_by(id: params[:id])
    render template: "photos/edit"
  end

  def update
    @photo = Photo.find_by(id: params[:id])
    @photo.name = params[:photo][:name]
    @photo.born = params[:photo][:born]
    @photo.description = params[:photo][:description]
    @photo.save
    redirect_to "/photos"
  end

  def destroy
    @photo = Photo.find_by(id: params[:id])
    @photo.destroy
    redirect_to "/photos", status: :see_other
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new" #show form to login
  end

  def create # called when "new" is submitted? allows login and sets user_id
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to "/photos"
    else
      redirect_to "/login"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
  end

  def create
    @user = User.new(
      name: params[:user][:name],
      email: params[:user][:email],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )

    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FamilyTree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  <!-- css -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
     <!-- javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with model: @photo do |form| %>
  <div>
    <%= form.label :name%>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :born %>
    <%= form.text_field :born %>
  </div>
  <div>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1> Edit Photo </h1>

<%= render "form", article: @article %>

app/views/photos/index.html.erb
<h1> All Photos </h1>



<%= link_to "New photo", new_photo_path(@photo) %>
<div class = "row">
<% @photos.each do |photo| %>


<div class = "col">
<h2> <%= photo.name %></h2>
<%= image_tag ("#{photo.name}.png"), width: "100" %>
<p>Born: <%= photo.born %></p>
<%= link_to "More Info", photo %>
</div>
<% end %>
</div>


<style>
  body{
    font-family: serif;
  }
</style>

app/views/photos/new.html.erb
<h1> New Photo Form </h1>

<%= render "form", article: @article %>

app/views/photos/show.html.erb
<h1>Photo Info</h1>

<h2><%= @photo.name %> </h2>
<%= image_tag ("#{@photo.name}.png")%>
<p>Blurb: <%= @photo.description %></p>
<p>Born: <%= @photo.born %></p>

<a href="/photos">Back to all photos</a>
<%= link_to "Edit photo", edit_photo_path(@photo) %>
<%= link_to "Destroy photo", photo_path(@photo), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

app/views/users/new.html.erb
<h1>Signup</h1>
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <% @user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
    <% @user.errors.full_messages_for(:email).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
    <% @user.errors.full_messages_for(:password_confirmation).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>